### PR TITLE
Cleanup HTML

### PR DESCRIPTION
**Pull request by nojb**
Hello!

Thanks for your initiative. I took a look at the `index.html` file and it contained a lot of code copy/pasted from the `www.walden.org` site and in particular a lot of unused/no-longer existing links which made the site load very slowly.

I removed a lot of code that was not used and broken links, so that the site loads instantly now. There is a lot more lot to clean up, but this is a start at least. The site should look exactly the same after these changes.

### CODE REVIEW

**Comment by DavidMichaelRoberts** [comment]
Thanks for this! I noticed the site was loading reeeally slowly.

**Comment by nojb** [comment]
Friendly ping.

**Comment by carmonamateo** [comment]
Oh sorry, I was very busy lately. I haven’t seen this yet. Many thanks

**Review by carmonamateo — APPROVED** [review]

**Comment by carmonamateo** [comment]
There are conflicts I do not know how to resolve...

**Comment by nojb** [comment]
> There are conflicts I do not know how to resolve...

I pushed an updated version which applies cleanly to `master`. Thanks!

**Pull request merged**
